### ISSUE TITLE
Замечания по заданию 1

### ISSUE THREAD

**Issue by ivan-uskov** [KirillVeresnikov/AboutMe#1]
1) Молодец что проявил инициативу с выгрузкой данных из VK. Но нужно сделать это правильно. Стоит сделать класс VKDataProvider, который разместить в папке src/DataProvider, в него перенести логику из папки include. Также стоит сделать класс VKUserInfo, который будет хранить информацию о пользователе, это необходимо чтобы контроллер не знал внутреннюю структуру получаемых от VK данных. Получается что VKDataProvider будет получать информацию, парсить её и возвращать VKUserInfo. А контроллер из VKUserInfo получать информацию

2) base.html.twig существует и нигде не используется

**Comment by KirillVeresnikov** [comment]
Исправлено
https://github.com/KirillVeresnikov/AboutMe/commit/d4dbd40af845ec534abba571c7383e920a4a37ce

**Comment by ivan-uskov** [comment]
1) 1 класс 1 файл, не нужно несколько классов в один файл складывать
2) Название файла должно совпадать с названием класса
3) Название переменных и методов должно начинаться с маленькой буквы
4)  $this -> list в таких конструкциях все пишется слитно
